# Generated by Django 4.0.3 on 2022-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctionlistings_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='username',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
