# Generated by Django 4.0.3 on 2022-04-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_bid_bids_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.listings'),
            preserve_default=False,
        ),
    ]
