# Generated by Django 4.0.3 on 2022-04-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction',
            new_name='listing',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watching',
        ),
    ]
